"""change score to float

Revision ID: 03ebbd95b3ad
Revises: 67fb365d837b
Create Date: 2024-10-11 14:12:53.570906

"""

# Import standard library modules
from typing import Sequence, Union

# Import third-party library modules
import sqlalchemy as sa

# Import local modules
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03ebbd95b3ad"
down_revision: Union[str, None] = "67fb365d837b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "AgentConversationSessionMetadata",
        "receptionScore",
        existing_type=sa.DECIMAL(precision=18, scale=0),
        type_=sa.Float(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "AgentConversationSessionMetadata",
        "receptionScore",
        existing_type=sa.Float(),
        type_=sa.DECIMAL(precision=18, scale=0),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
