"""add user and analytics event

Revision ID: 5a9e362043e2
Revises:
Create Date: 2024-08-30 02:35:48.134349

"""

# Import standard library modules
from typing import Sequence, Union

# Import third-party library modules
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# Import local modules
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a9e362043e2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "AnalyticsEvent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("eventName", sa.NVARCHAR(length=1000), nullable=False),
        sa.Column("user", sa.NVARCHAR(length=1000), nullable=True),
        sa.Column("dateCreated", mssql.DATETIME2(), nullable=False),
        sa.Column("eventTrigger", sa.NVARCHAR(length=1000), nullable=True),
        sa.Column("eventMetadata", sa.NVARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "eventName_dateCreated_idx",
        "AnalyticsEvent",
        ["eventName", "dateCreated"],
        unique=False,
    )
    op.create_table(
        "User",
        sa.Column("id", sa.NVARCHAR(length=1000), autoincrement=False, nullable=False),
        sa.Column("name", sa.NVARCHAR(length=1000), nullable=True),
        sa.Column("email", sa.NVARCHAR(length=1000), nullable=True),
        sa.Column("email_verified", mssql.DATETIME2(), nullable=True),
        sa.Column("image", sa.NVARCHAR(length=1000), nullable=True),
        sa.Column("createdAt", mssql.DATETIME2(), nullable=False),
        sa.Column("updatedAt", mssql.DATETIME2(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("User")
    op.drop_index("eventName_dateCreated_idx", table_name="AnalyticsEvent")
    op.drop_table("AnalyticsEvent")
    # ### end Alembic commands ###
