"""update decimal precision

Revision ID: 67fb365d837b
Revises: 826d7efa32e9
Create Date: 2024-10-10 16:02:28.769636

"""

# Import standard library modules
from typing import Sequence, Union

# Import third-party library modules
import sqlalchemy as sa

# Import local modules
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67fb365d837b"
down_revision: Union[str, None] = "826d7efa32e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
