"""add librarian tables

Revision ID: f855013dd732
Revises: 5a9e362043e2
Create Date: 2024-08-30 06:29:34.968707

"""

# Import standard library modules
from typing import Sequence, Union

# Import third-party library modules
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# Import local modules
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f855013dd732"
down_revision: Union[str, None] = "5a9e362043e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "KnowledgebaseConversation",
        sa.Column("id", sa.NVARCHAR(length=1000), autoincrement=False, nullable=False),
        sa.Column("title", sa.NVARCHAR(length=1000), nullable=False),
        sa.Column("userId", sa.NVARCHAR(length=1000), nullable=False),
        sa.Column("lastMessageDate", mssql.DATETIME2(), nullable=False),
        sa.Column("createdAt", mssql.DATETIME2(), nullable=False),
        sa.Column("updatedAt", mssql.DATETIME2(), nullable=False),
        sa.Column("deletedAt", mssql.DATETIME2(), nullable=True),
        sa.Column("pinnedAt", mssql.DATETIME2(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "KnowledgebaseMessage",
        sa.Column("id", sa.NVARCHAR(length=1000), autoincrement=False, nullable=False),
        sa.Column("conversationId", sa.NVARCHAR(length=1000), nullable=False),
        sa.Column("is_bot", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("text", sa.NVARCHAR(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Boolean(), nullable=True),
        sa.Column("ratingData", sa.NVARCHAR(), nullable=True),
        sa.Column("ratingText", sa.NVARCHAR(), nullable=True),
        sa.Column("createdAt", mssql.DATETIME2(), nullable=False),
        sa.Column("deletedAt", mssql.DATETIME2(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversationId"],
            ["KnowledgebaseConversation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "KnowledgebaseMessageSource",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("messageId", sa.NVARCHAR(length=1000), nullable=False),
        sa.Column("link", sa.NVARCHAR(length=1000), nullable=False),
        sa.Column("filename", sa.NVARCHAR(length=1000), nullable=False),
        sa.Column("chunks", sa.NVARCHAR(), nullable=False),
        sa.Column("dateIngested", mssql.DATETIME2(), nullable=False),
        sa.Column("dateCreated", mssql.DATETIME2(), nullable=False),
        sa.Column("dateDeleted", mssql.DATETIME2(), nullable=True),
        sa.ForeignKeyConstraint(
            ["messageId"],
            ["KnowledgebaseMessage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "KnowledgebaseMessageSuggestion",
        sa.Column("id", sa.NVARCHAR(length=1000), autoincrement=False, nullable=False),
        sa.Column("suggestion", sa.NVARCHAR(), nullable=False),
        sa.Column("createdAt", mssql.DATETIME2(), nullable=True),
        sa.Column("messageId", sa.NVARCHAR(length=1000), nullable=False),
        sa.ForeignKeyConstraint(
            ["messageId"],
            ["KnowledgebaseMessage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "KnowledgebaseRewriteResponse",
        sa.Column("id", sa.NVARCHAR(length=1000), autoincrement=False, nullable=False),
        sa.Column("messageId", sa.NVARCHAR(length=1000), nullable=False),
        sa.Column("instruction", sa.NVARCHAR(length=1000), nullable=False),
        sa.Column("rewriteText", sa.NVARCHAR(), nullable=False),
        sa.Column("createdAt", mssql.DATETIME2(), nullable=False),
        sa.ForeignKeyConstraint(
            ["messageId"],
            ["KnowledgebaseMessage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("KnowledgebaseRewriteResponse")
    op.drop_table("KnowledgebaseMessageSuggestion")
    op.drop_table("KnowledgebaseMessageSource")
    op.drop_table("KnowledgebaseMessage")
    op.drop_table("KnowledgebaseConversation")
    # ### end Alembic commands ###
