def get_dummy_customers():
    dummy_customers = [
        {
            "full_name": "Maria Santos",
            "age": "45-49",
            "birthday": "March 17, 1977",
            "gender_code": "F",
            "nationality_desc": "FILIPINO",
            "occupation_desc": "ADMINISTRATOR/MANAGER",
            "industry": "Healthcare",
            "fund_source_desc": "Multiple",
            "marital_status_description": "MARRIED",
            "dependents": 1,
            "city_home_final": "DAVAO",
            "city_work_final": "DAVAO",
            "mobile_number": 9173357890,
            "email_address": "mariasantos@gmail.com",
            "customer_segment": "fitness_enthusiast",
            "channels": "branch visit, contact center, website",
            "preferred_communications_channel": "phone call, SMS",
            "average_daily_balance": 2000000,
            "range_of_account_balance": "1800000-2400000",
            "top_spending_past_3_months": "wellness, beauty, hotel",
            "products_availed": "Savings Account, High Yield Savings, Rewards Credit Card, Corporate Credit Card, Investment Account",
            "recommend_rewards_card": "unlikely",
            "recommend_gold_rewards_card": "highly likely",
            "recommend_ecredit_card": "unlikely",
            "recommend_corporate_card": "unlikely",
            "recommend_signature_card": "unlikely",
        },
        {
            "full_name": "Daniel Jose",
            "age": "30-34",
            "birthday": "February 15, 1994",
            "gender_code": "M",
            "nationality_desc": "FILIPINO",
            "occupation_desc": "PROFESSIONAL",
            "industry": "Financial Services",
            "fund_source_desc": "Salary/Compensation",
            "marital_status_description": "UNMARRIED",
            "dependents": 0,
            "city_home_final": "MAKATI",
            "city_work_final": "NCR",
            "mobile_number": 9777887321,
            "email_address": "daniel21.jose@gmail.com",
            "customer_segment": "avid_traveler",
            "channels": "branch visit",
            "preferred_communications_channel": "SMS",
            "average_daily_balance": 300000,
            "range_of_account_balance": "220000-380000",
            "top_spending_past_3_months": "airfare, hotel, groceries",
            "products_availed": "Savings Account, Gold Rewards Credit Card",
            "recommend_rewards_card": "unlikely",
            "recommend_gold_rewards_card": "unlikely",
            "recommend_ecredit_card": "likely",
            "recommend_corporate_card": "unlikely",
            "recommend_signature_card": "likely",
        },
        {
            "full_name": "Daniel Jose",
            "age": "45-49",
            "birthday": "November 12, 1978",
            "gender_code": "M",
            "nationality_desc": "FILIPINO",
            "occupation_desc": "ENGINEER",
            "industry": "Construction",
            "fund_source_desc": "Salary/Compensation",
            "marital_status_description": "UNMARRIED",
            "dependents": 0,
            "city_home_final": "CEBU",
            "city_work_final": "CEBU",
            "mobile_number": 9176554321,
            "email_address": "liamreyes@gmail.com",
            "customer_segment": "tech_savvy",
            "channels": "branch visit, mobile app, website",
            "preferred_communications_channel": "email",
            "average_daily_balance": 400000,
            "range_of_account_balance": "300000-500000",
            "top_spending_past_3_months": "gadgets, travel, dining",
            "products_availed": "Savings Account, Gold Rewards Credit Card",
            "recommend_rewards_card": "likely",
            "recommend_gold_rewards_card": "unlikely",
            "recommend_ecredit_card": "likely",
            "recommend_corporate_card": "unlikely",
            "recommend_signature_card": "unlikely",
        },
        {
            "full_name": "Manuel Ortega",
            "age": "20-24",
            "birthday": "June 5, 1999",
            "gender_code": "M",
            "nationality_desc": "FILIPINO",
            "occupation_desc": "ANALYST",
            "industry": "IT",
            "fund_source_desc": "Salary/Compensation",
            "marital_status_description": "UNMARRIED",
            "dependents": 0,
            "city_home_final": "MANILA",
            "city_work_final": "NCR",
            "mobile_number": 9177689109,
            "email_address": "manuelortega@gmail.com",
            "customer_segment": "young_professional",
            "channels": "branch visit, mobile app, website",
            "preferred_communications_channel": "<no data>",
            "average_daily_balance": 70000,
            "range_of_account_balance": "50000-100000",
            "top_spending_past_3_months": "gadgets, clothes, ride-hailing",
            "products_availed": "Savings Account",
            "recommend_rewards_card": "highly likely",
            "recommend_gold_rewards_card": "unlikely",
            "recommend_ecredit_card": "likely",
            "recommend_corporate_card": "unlikely",
            "recommend_signature_card": "unlikely",
        },
        {
            "full_name": "Eduardo Gonzales",
            "age": "35-39",
            "birthday": "February 28, 1988",
            "gender_code": "M",
            "nationality_desc": "FILIPINO",
            "occupation_desc": "ADMINISTRATOR/MANAGER",
            "industry": "Government",
            "fund_source_desc": "Salary/Compensation",
            "marital_status_description": "MARRIED",
            "dependents": 2,
            "city_home_final": "MANILA",
            "city_work_final": "NCR",
            "mobile_number": 9175939666,
            "email_address": "eduardogonzales@gmail.com",
            "customer_segment": "gastronome",
            "channels": "branch visit, mobile app",
            "preferred_communications_channel": "<no data>",
            "average_daily_balance": 200000,
            "range_of_account_balance": "150000-250000",
            "top_spending_past_3_months": "restaurants, food delivery, groceries",
            "products_availed": "Savings Account, Rewards Credit Card, Individual Loan",
            "recommend_rewards_card": "unlikely",
            "recommend_gold_rewards_card": "highly likely",
            "recommend_ecredit_card": "unlikely",
            "recommend_corporate_card": "unlikely",
            "recommend_signature_card": "unlikely",
        },
        {
            "full_name": "Anna Cruz",
            "age": "45-49",
            "birthday": "September 21, 1975",
            "gender_code": "F",
            "nationality_desc": "FILIPINO",
            "occupation_desc": "SELF-EMPLOYED",
            "industry": "Food and Restaurants",
            "fund_source_desc": "Business",
            "marital_status_description": "MARRIED",
            "dependents": 1,
            "city_home_final": "MANILA",
            "city_work_final": "NCR",
            "mobile_number": 9266383640,
            "email_address": "annacruz@yahoo.com",
            "customer_segment": "business_owner",
            "channels": "branch visit",
            "preferred_communications_channel": "phone call",
            "average_daily_balance": 2000000,
            "range_of_account_balance": "1500000-2500000",
            "top_spending_past_3_months": "airfare, wellness, utilities",
            "products_availed": "Savings Account, Current Account, Gold Rewards Card, Investment Account",
            "recommend_rewards_card": "unlikely",
            "recommend_gold_rewards_card": "unlikely",
            "recommend_ecredit_card": "unlikely",
            "recommend_corporate_card": "highly likely",
            "recommend_signature_card": "likely",
        },
        {
            "full_name": "Maria Santos",
            "age": "30-34",
            "birthday": "July 10, 1994",
            "gender_code": "F",
            "nationality_desc": "FILIPINO",
            "occupation_desc": "SELF-EMPLOYED",
            "industry": "Retail",
            "fund_source_desc": "Business",
            "marital_status_description": "MARRIED",
            "dependents": 2,
            "city_home_final": "QUEZON",
            "city_work_final": "NCR",
            "mobile_number": 9174556789,
            "email_address": "maria_santos@gmail.com",
            "customer_segment": "fitness_enthusiast",
            "channels": "branch visit, mobile app, website",
            "preferred_communications_channel": "SMS",
            "average_daily_balance": 1500000,
            "range_of_account_balance": "1200000-1800000",
            "top_spending_past_3_months": "clothing, electronics, dining",
            "products_availed": "Savings Account, Current Account, Rewards Credit Card, Investment Account",
            "recommend_rewards_card": "unlikely",
            "recommend_gold_rewards_card": "highly likely",
            "recommend_ecredit_card": "likely",
            "recommend_corporate_card": "unlikely",
            "recommend_signature_card": "unlikely",
        },
    ]

    return dummy_customers
